# Save as Config.yml for running GeoTIFFfromHPD

HPDConnection:
  User: ''                           #HPD Oracle User ID 
  PW: ''                             #HPD Oracle User password
  dsn: ''                            #HPD Host server
  port: ''                           #HPD Oracle port number
  DBname: ''                         #HPD Oracle DB instance name

Datasets:
  Charts: [NZ561] #Chart name as [NZ6825, ]
#Test NZ4424,NZ4432,NZ51,NZ512,NZ5121,NZ5125,NZ52,NZ521,NZ5212,NZ5322,NZ5324,NZ541,NZ5411
# NO RNC, Dup NZ4212
LDSConnection:
  host: ''
  token: ''
  config: ''
